<?php
use voku\AgentLearning\Catalog\TaskLearningProjection;
use voku\AgentUi\Feature\Knowledge\DeliveredPrecedents;
use voku\AgentUi\Integration\AgentLearning\TaskPrecedentSnapshot;
use voku\AgentUi\View\Presentation;
use voku\AgentUi\View\TemplateRenderer;
/** @var array{learning: TaskLearningProjection, precedents: TaskPrecedentSnapshot, delivered: DeliveredPrecedents} $model */
$learning = $model['learning'];
$taskContext = $model['task_context'];
$precedents = $model['precedents'];
$delivered = $model['delivered'];
$title = $learning->taskId . ' · Learning · agent-ui';
$nav = null;
$projectLabel = null;
require __DIR__ . '/../layout/header.php';
?>
<p class="crumbs"><a href="/board">Board</a><span>/</span><a href="/task/<?= TemplateRenderer::escape($learning->taskId) ?>"><?= TemplateRenderer::escape($learning->taskId) ?></a><span>/</span>Learning</p>
<?php $taskNavCurrent = '/learning'; require __DIR__ . '/../layout/task-context.php'; ?>
<div class="page-head"><h1>What this task taught us</h1><p class="lede">Lineage appears here only where its owner recorded it: agent-learning for Findings, notes and what became durable, and agent-recall-compiler for which precedents were delivered to this task. Missing links remain unknown rather than being guessed from filenames or text.</p></div>
<p class="eyebrow">Findings</p><section class="panel"><?php if ($learning->findings === []): ?><p class="empty">No Learning Finding is linked to this task.</p><?php else: ?><div class="stack"><?php foreach ($learning->findings as $finding): ?><article><div class="action__head"><a class="mono" href="/knowledge/findings/<?= TemplateRenderer::escape($finding->id) ?>"><?= TemplateRenderer::escape($finding->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($finding->status)) ?>"><?= TemplateRenderer::escape(Presentation::label($finding->status)) ?></span></div><p class="small" style="margin:6px 0 0"><?= TemplateRenderer::escape($finding->observation) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
<p class="eyebrow">Learning notes</p><section class="panel"><?php if (!$precedents->isAvailable()): ?><p class="empty" role="status"><?= TemplateRenderer::escape((string) $precedents->problem) ?></p><?php elseif ($precedents->taughtNotes() === []): ?><p class="empty">No LearningNote is derived from this task's lineage.</p><?php else: ?><div class="stack"><?php foreach ($precedents->taughtNotes() as $note): ?><article><div class="action__head"><span class="mono"><?= TemplateRenderer::escape($note->id) ?></span><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($note->status->value)) ?>"><?= TemplateRenderer::escape(Presentation::label($note->status->value)) ?></span><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($note->evidenceState->value)) ?>">evidence <?= TemplateRenderer::escape(Presentation::label($note->evidenceState->value)) ?></span></div><p style="margin:6px 0 0"><strong><?= TemplateRenderer::escape($note->content->title) ?></strong></p><p class="small" style="margin:4px 0 0"><?= TemplateRenderer::escape($note->content->guidance) ?></p><p class="note" style="margin-top:4px">pattern <code><?= TemplateRenderer::escape($note->patternKey) ?></code> · from <?php foreach ($note->sourceFindings as $index => $findingId): ?><?= $index > 0 ? ', ' : '' ?><a class="mono" href="/knowledge/findings/<?= TemplateRenderer::escape($findingId) ?>"><?= TemplateRenderer::escape($findingId) ?></a><?php endforeach; ?></p></article><?php endforeach; ?></div><p class="note">A note is precedent, not policy: it is recalled for later tasks as historical context and carries no authority until a reviewed Proposal makes it durable. Whether a later task received it is shown on that task's <em>Context</em> page.</p><?php endif; ?></section>
<p class="eyebrow">Precedents Recall delivered</p><section class="panel"><?php if ($delivered->status !== DeliveredPrecedents::AVAILABLE): ?><p class="empty" role="status"><?= TemplateRenderer::escape((string) $delivered->problem) ?></p><?php elseif ($delivered->items === []): ?><p class="empty">No learning precedent was part of this task's compiled Recall context.</p><?php else: ?><div class="stack"><?php foreach ($delivered->items as $precedent): ?><article><div class="action__head"><strong><?= TemplateRenderer::escape($precedent->title) ?></strong><span class="pill pill--<?= $precedent->delivered ? 'ok' : 'neutral' ?>"><?= $precedent->delivered ? 'delivered' : 'not delivered' ?></span><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($precedent->state)) ?>">evidence <?= TemplateRenderer::escape(Presentation::label($precedent->state)) ?></span></div><?php if ($precedent->whyNot !== null): ?><p class="small" style="margin:6px 0 0">Why not delivered: <?= TemplateRenderer::escape($precedent->whyNot) ?></p><?php endif; ?><p class="note" style="margin-top:4px"><?php if ($precedent->taughtBy === null || $precedent->taughtBy === []): ?><?= TemplateRenderer::escape($precedent->originNote) ?><?php else: ?>Taught by <?php foreach ($precedent->taughtBy as $index => $originTask): ?><?= $index > 0 ? ', ' : '' ?><a class="mono" href="/task/<?= TemplateRenderer::escape($originTask) ?>/learning"><?= TemplateRenderer::escape($originTask) ?></a><?php endforeach; ?> (note → source Finding → task, as agent-learning records it).<?php endif; ?></p></article><?php endforeach; ?></div><p class="note">Delivery is shown, not effect: Recall reports that the note was put in front of this task. Nothing recorded here says the work used it or that it changed the outcome.</p><?php endif; ?></section>
<p class="eyebrow">Proposals</p><section class="panel"><?php if ($learning->proposals === []): ?><p class="empty">No proposal is linked through this task's Findings.</p><?php else: ?><div class="stack"><?php foreach ($learning->proposals as $proposal): ?><article><div class="action__head"><a class="mono" href="/knowledge/proposals/<?= TemplateRenderer::escape($proposal->id) ?>"><?= TemplateRenderer::escape($proposal->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($proposal->status)) ?>"><?= TemplateRenderer::escape(Presentation::label($proposal->status)) ?></span></div><p class="small" style="margin:6px 0 0"><?= TemplateRenderer::escape($proposal->reason) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
<p class="eyebrow">Guidance from this lineage</p><section class="panel"><?php if ($learning->guidance === []): ?><p class="empty">No memory, skill or constraint projection is linked through this task's proposals.</p><?php else: ?><div class="stack"><?php foreach ($learning->guidance as $guidance): ?><article><div class="action__head"><a class="mono" href="/knowledge/guidance/<?= TemplateRenderer::escape($guidance->id) ?>"><?= TemplateRenderer::escape($guidance->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($guidance->status)) ?>"><?= TemplateRenderer::escape($guidance->type->value . ' · ' . Presentation::label($guidance->status)) ?></span></div><p class="note" style="margin-top:4px">helpful <?= $guidance->usage->helpful ?> · irrelevant <?= $guidance->usage->irrelevant ?> · harmful <?= $guidance->usage->harmful ?> · violations <?= $guidance->usage->violationDetected ?></p></article><?php endforeach; ?></div><?php endif; ?><p class="note">Status stays explicit: a rejected proposal may still have a guidance-shaped projection for historical inspection; that does not make it durable.</p></section>
<p class="eyebrow">Outcome records</p><section class="panel"><?php if ($learning->outcomeIds === []): ?><p class="empty">No task-linked outcome record IDs are projected.</p><?php else: ?><div class="stack"><?php foreach ($learning->outcomeIds as $id): ?><code><?= TemplateRenderer::escape($id) ?></code><?php endforeach; ?></div><?php endif; ?><p class="note">Outcome identity is shown without inventing a second outcome parser in agent-ui.</p></section>
<?php require __DIR__ . '/../layout/footer.php'; ?>
