<?php
use voku\AgentLearning\Catalog\TaskLearningProjection;
use voku\AgentUi\View\Presentation;
use voku\AgentUi\View\TemplateRenderer;
/** @var array{learning: TaskLearningProjection} $model */
$learning = $model['learning'];
$title = $learning->taskId . ' · Learning · agent-ui';
$nav = null;
$projectLabel = null;
require __DIR__ . '/../layout/header.php';
?>
<p class="crumbs"><a href="/board">Board</a><span>/</span><a href="/task/<?= TemplateRenderer::escape($learning->taskId) ?>"><?= TemplateRenderer::escape($learning->taskId) ?></a><span>/</span>Learning</p>
<div class="page-head"><span class="page-head__id"><?= TemplateRenderer::escape($learning->taskId) ?></span><h1>What this task taught us</h1><p class="lede">Only lineage explicitly recorded by agent-learning appears here. Missing links remain unknown rather than being guessed from filenames or text.</p></div>
<p class="eyebrow">Findings</p><section class="panel"><?php if ($learning->findings === []): ?><p class="empty">No Learning Finding is linked to this task.</p><?php else: ?><div class="stack"><?php foreach ($learning->findings as $finding): ?><article><div class="action__head"><a class="mono" href="/knowledge/findings/<?= TemplateRenderer::escape($finding->id) ?>"><?= TemplateRenderer::escape($finding->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($finding->status)) ?>"><?= TemplateRenderer::escape(Presentation::label($finding->status)) ?></span></div><p class="small" style="margin:6px 0 0"><?= TemplateRenderer::escape($finding->observation) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
<p class="eyebrow">Proposals</p><section class="panel"><?php if ($learning->proposals === []): ?><p class="empty">No proposal is linked through this task's Findings.</p><?php else: ?><div class="stack"><?php foreach ($learning->proposals as $proposal): ?><article><div class="action__head"><a class="mono" href="/knowledge/proposals/<?= TemplateRenderer::escape($proposal->id) ?>"><?= TemplateRenderer::escape($proposal->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($proposal->status)) ?>"><?= TemplateRenderer::escape(Presentation::label($proposal->status)) ?></span></div><p class="small" style="margin:6px 0 0"><?= TemplateRenderer::escape($proposal->reason) ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
<p class="eyebrow">Durable guidance from this lineage</p><section class="panel"><?php if ($learning->guidance === []): ?><p class="empty">No memory, skill or constraint is linked through this task's proposals.</p><?php else: ?><div class="stack"><?php foreach ($learning->guidance as $guidance): ?><article><div class="action__head"><a class="mono" href="/knowledge/guidance/<?= TemplateRenderer::escape($guidance->id) ?>"><?= TemplateRenderer::escape($guidance->id) ?></a><span class="pill pill--<?= TemplateRenderer::escape(Presentation::tone($guidance->status)) ?>"><?= TemplateRenderer::escape($guidance->type->value . ' · ' . Presentation::label($guidance->status)) ?></span></div><p class="note" style="margin-top:4px">helpful <?= $guidance->usage->helpful ?> · irrelevant <?= $guidance->usage->irrelevant ?> · harmful <?= $guidance->usage->harmful ?> · violations <?= $guidance->usage->violationDetected ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
<p class="eyebrow">Outcome records</p><section class="panel"><?php if ($learning->outcomeIds === []): ?><p class="empty">No task-linked outcome record IDs are projected.</p><?php else: ?><div class="stack"><?php foreach ($learning->outcomeIds as $id): ?><code><?= TemplateRenderer::escape($id) ?></code><?php endforeach; ?></div><?php endif; ?><p class="note">Outcome identity is shown without inventing a second outcome parser in agent-ui.</p></section>
<div class="btn-row"><a class="btn" href="/knowledge">Knowledge</a><a class="btn" href="/task/<?= TemplateRenderer::escape($learning->taskId) ?>">← Task</a></div>
<?php require __DIR__ . '/../layout/footer.php'; ?>
